class MixOrMatch{
    constructor(totalTime,cards){
        this.totalTime=totalTime;
        this.cards=cards;
        this.timer=document.getElementById('time-remaining');
        this.ticker=document.getElementById('flips')
        this.matched=false;
        this.totalFlips=0;
        this.matchedCards=[];
        this.cardToCheck=null;
    }
    hideCards(){
        this.cards.forEach((card)=>{
            card.classList.remove('visible');
            card.classList.remove('matched');
        })
    }
    runningGame(){
        this.busy=true;
        return setTimeout(()=>{
            this.startCountDown();
            this.busy=false;
        })
    }
    startCountDown(){
        console.log(this.totalTime--)
        this.timer.innerText=this.totalTime;
    }
    flipCard(card){
        if(!this.busy&&!this.matchedCards.includes(card)&&card!==this.cardToCheck){
            this.totalFlips++
            this.ticker.textContent=this.totalFlips;
            card.classList.add('visible');
            if(this.cardToCheck){
                if(card.getElementsByClassName('card-value')[0].id===this.cardToCheck.getElementsByClassName('card-value')[0].id){
                    this.matchedCards.push(card);
                    this.matchedCards.push(this.cardToCheck);
                    card.classList.add('matched');
                    this.cardToCheck.classList.add('matched');
                }else{
                    this.busy=true
                    setTimeout(()=>{
                        card.classList.remove('visible');
                        this.cardToCheck.classList.remove('visible');
                        this.busy=false
                    },1000)
                }
                this.cardToCheck=null
            }else{
                this.cardToCheck=card
            }
        }
    };
}
function ready(){
    const cards=Array.from(document.getElementsByClassName('card'))
    const overlays=Array.from(document.getElementsByClassName('overlay-text'))
    const games=new MixOrMatch(100,cards)
    overlays.forEach((overlay)=>{
        overlay.addEventListener('click',()=>{
            overlay.classList.remove('visible');
            games.runningGame();
        })
    })
    cards.forEach(card=>{
        card.addEventListener('click',()=>{
            games.flipCard(card)
        })
    })
}
ready();